CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

-- list al tables
\dt

-- list all data in projects table
SELECT * FROM projects;

-- INSERT TEST DATA FOR projects
INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Crear una Web', 1, 'Usar Javascript', '2022-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Crear una App', 1, 'Usar Javascript', '2022-07-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a Desktop App', 2, 'Usar Javascript', '2022-06-12');

-- INSERT TEST DATA FOR tasks
INSERT INTO tasks(name, done, projectId)
    VALUES('Descargar Vuejs', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Descargar Nuxt', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Descargar Php', false, 2);

INSERT INTO tasks(name, done, projectId)
    VALUES('Descargar C++', false, 2);

select * from tasks;

select * from tasks where projectId = 1;